import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import styled from "styled-components";
import Link from "next/link";

const H1 = styled.h1`
  color: red;
`;

const Links = styled.div`
  margin-top: 16px;
  display: grid;
  grid-template-columns: 1fr;
  gap: 8px;

  & a {
    text-decoration: underline;
  }
`

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <H1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </H1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div>
          <span>다음은 styled-component의 각 샘플 코드의 페이지로의 링크입니다</span>
          <Links>
            <Link href="/badge">
              <a>Badge 예</a>
            </Link>
            <Link href="/props-sample">
              <a>props를 사용한 예</a>
            </Link>
            <Link href="/mixin-sample">
              <a>mixin을 사용한 예</a>
            </Link>
            <Link href="/inheritance-sample">
              <a>상속을 사용한 예</a>
            </Link>
            <Link href="/as-sample">
              <a>스타일을 다른 컴포넌트에서 사용한 예</a>
            </Link>
            <Link href="/styled-link-sample">
              <a>Next.js의 컴포넌트에 스타일을 적용한 예</a>
            </Link>
            <Link href="/theme-sample">
              <a>테마를 사용한 예</a>
            </Link>
          </Links>
        </div>
      </main>
    </div>
  );
};

export default Home;
